### ISSUE TITLE
1.1 Develop key push metrics document

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#1]
Define metrics are we using to identify funnel & engagement.
Attempt to determine a causality between DAU and Push Subscriptions.

**Comment by clarkbw** [comment]
A "push user" is counted as a user even 7 days after they receive a push notification. Mau & Dau use an approximation argument that have a 0.5% standard error, and the query is working on a 1% sample of all Firefox Users.

https://bugzilla.mozilla.org/show_bug.cgi?id=1269466
https://sql.telemetry.mozilla.org/queries/1667/source#2960
