### ISSUE TITLE
5.4 Integration tests for bridges to external Push systems

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#17]
We should have a full suite of integration tests for our GCM/FCM/APNS bridges that is run automatically by our Travis-CI.

**Comment by jrconlin** [comment]
Partially resolved by: https://github.com/mozilla-services/autopush/pull/716

This PR adds integration tests for bridge calls, however still requires some Mock use. These intercept at as close to transmit and receive as possible.

**Comment by jrconlin** [comment]
On further review of the code and implementation, the prior patch should be sufficient.

The above patch lets code work right up to the point where we call out to the services. While I've created [mock versions of the FCM/GCM service](https://github.com/jrconlin/mocks), those can only replicate known states and not the level of behavior from using a live service, and cannot replicate unknown states. Even then, these could fail aspects that are unknown (like internal routing issues or errors of that remote service). Live service use would require a known device to be paired as if in production.

**Comment by jrconlin** [comment]
resolved completed.
