### ISSUE TITLE
1.1 Create document outlining information we want to know about and external team dependencies to acquire the information.

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-okr#18]
Create document outlining information we want to know about and external team dependencies to acquire the information.

**Comment by bbangert** [comment]
https://www.google.com/url?q=https://drive.google.com/open?id%3D1wduNFqF_EaDhaiOfR3u8lCAbrS1-CvrK3Ecbkmkkeo0&sa=D&ust=1488581588198000&usg=AFQjCNG7SO-l_lpxFJBiHaG-tVN7qYveKA
