### ISSUE TITLE
1.4 Dashboard of Quality of Service

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-okr#21]
* Simple dashboard indicating server availability & use for the service as a whole. Including error rates, profile timing for transaction latency, etc.
* Data on nginx cache hits vs. not
* 95 and 99 percentile timings for message delivery
* 95 and 99 percentile round-trip latency
* Error rates
* Time to Deliver from storage vs. online
* Message delivery timing breakdowns based on message destination
* Heavy senders by IP/User-Agent
* Odd URL targets (Excessive messages to small groups of URL’s)

**Comment by bbangert** [comment]
Obsolete by updated OKR's.
