### ISSUE TITLE
3.1 Additional bridge API methods provided...

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#33]
3.1 Additional bridge API methods provided to help the client team understand errors they are receiving on the server side. 

https://github.com/mozilla-services/autopush/commit/71035fa0e95825c1058d1c3d8debade519c50c2a
https://github.com/mozilla-services/autopush/pull/858

**Comment by jrconlin** [comment]
added https://github.com/mozilla-services/autopush/pull/847
