### ISSUE TITLE
3.3 Retire SimplePush

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#47]
Issues:

- [x] mozilla-services/autopush#799

Related PR's:

- [x] mozilla-services/autopush/pull/981

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/autopush/issues/799

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/autopush/pull/981

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/autopush/pull/1023
