### ISSUE TITLE
1.5 Setup and hold a meeting with DevRel for Hacks post on Topics

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#5]
Setup and hold a meeting with DevRel about possible Hacks post on new Topic functionality.

**Comment by clarkbw** [comment]
Had a meeting on Monday, October 24th.

DevRel requires a demo setup so they can create a couple gifs to help explain how this work.

**Comment by clarkbw** [comment]
@jrconlin is working on the demo setup

**Comment by bbangert** [comment]
Posted on https://hacks.mozilla.org/2016/11/mozilla-push-server-now-supports-topics/
